apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-personalization
spec:
  template:
    spec:
      containers:
      - name: ai-personalization
        livenessProbe:
          httpGet:
            path: /health
            port: 3010
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3010
          initialDelaySeconds: 5
          periodSeconds: 5
