apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
spec:
  template:
    spec:
      containers:
      - name: main-app
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
