# GitHub Sponsors
github: Sizwe780

# Open Collective
open_collective: azora-os

# Ko-fi
ko_fi: azoraos

# Patreon
patreon: azoraos

# Custom funding links
custom:
  - https://azora.world/donate
  - https://azora.world/citadel-fund
  - https://opencollective.com/azora-os