apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azora-es
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sizwe780/azora-os
    path: infrastructure/k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true