apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vigil.fullname" . }}-config
  labels:
    {{- include "vigil.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  UI_ORIGIN: {{ .Values.config.uiOrigin | quote }}