apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vigil.fullname" . }}
  labels:
    {{- include "vigil.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vigil.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vigil.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vigil.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: vigil-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.config.nodeEnv }}
            - name: PORT
              value: {{ .Values.config.port | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "vigil.fullname" . }}-secrets
                  key: jwt-secret
            - name: UI_ORIGIN
              value: {{ .Values.config.uiOrigin }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "vigil.fullname" . }}-secrets
                  key: database-url
            - name: MQTT_BROKER
              value: {{ .Values.config.mqtt.broker }}
            - name: KAFKA_BROKERS
              value: {{ .Values.config.kafka.brokers }}
            {{- if .Values.config.azure.eventGrid.topic }}
            - name: AZURE_EVENTGRID_TOPIC
              value: {{ .Values.config.azure.eventGrid.topic }}
            - name: AZURE_EVENTGRID_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "vigil.fullname" . }}-secrets
                  key: azure-eventgrid-key
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}