apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vigil.fullname" . }}-secrets
  labels:
    {{- include "vigil.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc }}
  database-url: {{ printf "postgres://%s:%s@%s:%d/%s" .Values.config.database.user .Values.secrets.dbPassword .Values.config.database.host .Values.config.database.port .Values.config.database.name | b64enc }}
  {{- if .Values.secrets.azureEventGridKey }}
  azure-eventgrid-key: {{ .Values.secrets.azureEventGridKey | b64enc }}
  {{- end }}