---
name: Security Vulnerability
about: Report a security vulnerability
title: "[SECURITY] "
labels: security
assignees: ''

---

## Vulnerability Description
Provide a clear and concise description of the security vulnerability.

## Impact
Describe the potential impact of this vulnerability:
- What could an attacker do?
- What data could be compromised?
- What systems could be affected?

## Steps to Reproduce
Provide detailed steps to reproduce the vulnerability. **DO NOT** include exploits or proof-of-concept code that could be used maliciously.

## Proof of Concept
If you have a safe proof of concept that demonstrates the vulnerability without enabling exploitation, include it here.

## Affected Components
- Component/Service: [e.g., azora-nexus, azora-aegis]
- Version: [e.g., v1.0.0]
- Environment: [e.g., production, staging, development]

## Mitigation
If you know of any workarounds or fixes, please describe them here.

## Additional Information
Any additional context or information that might be helpful in understanding or addressing this vulnerability.

**Note:** Security reports are taken seriously. Please allow reasonable time for the team to investigate and respond.