version: '3.8'

services:
  domain-marketplace:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: domain-marketplace-service
    ports:
      - "3007:3007"
    environment:
      - PORT=3007
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/domain-marketplace
      - PROMETHEUS_METRICS_ENABLED=true
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - azora-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3007/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:6.0
    container_name: domain-marketplace-mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=domain-marketplace
    volumes:
      - mongodb_data:/data/db
      - ./docker/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - azora-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  azora-network:
    driver: bridge
    name: azora-network