name: Deploy Frontend to Vercel

on:
  push:
    branches: [main]
    paths: [ 'synapse/frontend/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: cd synapse/frontend && npm install
      - run: npm install -g vercel
      - run: cd synapse/frontend && vercel --token ${{ secrets.VERCEL_TOKEN }} --confirm --prod