name: Deploy Azora OS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker-compose -f deploy/docker-compose.yml build
          docker-compose -f deploy/docker-compose.yml push

      - name: Deploy services (Docker Compose)
        run: |
          docker-compose -f deploy/docker-compose.yml up -d

      - name: Health Check
        run: |
          chmod +x deploy.sh
          ./deploy.sh run_health_checks

      - name: Set up kubectl (optional, for k8s deploy)
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes (optional)
        if: ${{ env.K8S_DEPLOY == 'true' }}
        run: |
          kubectl apply -f deploy/k8s/
